# Generated by Django 4.2.1 on 2023-05-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_remove_task_id_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
